from exception.exercises import case_1


def main():
    print("Start app")

    case_1()

    print("Finish")


if __name__ == "__main__":
    main()
